/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It's automatically generated by Next.js
// It contains type definitions for Next.js
// If you need to extend Next.js types, create another file 